# library(tidyverse)
# library(cowplot)
# library(readr)
# library(data.table)
# library(stringr)
# 
# source("./All Functions - How to Survive a Killer Language.R")
# source("./Model 5.0 - How to Survive a Killer Language.R") # Run_ABM() lives here.




# library(jsonlite) # for writing json file that can store data as lists and allow it to be readable by the human eye. 



# Function to create a list of the default parameters that are (likely) to remain stable across model runs. 
get_default_params = function() {
  params <- list()
  params$generation_size <- 100
  params$generations_n <- 11
  params$languages_n <- 3
  params$speaker_freqs <- c(1/3, 1/3, 1/3)
  params$prop_of_intra_household_interactions <- 0.5
  params$parent_language_choice <- "random"
  params$child_language_choice <- "random"
  params$others_language_choice <- "random"
  
  return(params)
}



### Function to run the model a single time, creating a named output directory and a generating a random seed.
# This function creates an 'output directory' folder and inside it, it saves
# the random seed (.csv file)
# the list of parameters used in the model (.json file)
# the data frame of imaginary people and their language data generated by the model (.csv file)
run_model_single = function(params, output_directory, seed = NA) {
  
  #Create output directory
  if (dir.exists(output_directory)) {
    print("Warning: output directory already exists! Skipping simulation to avoid overwriting data.")
    return()
  } else {
    dir.create(output_directory, recursive=TRUE)
  }
  
  #If no seed is set, set it
  if (is.na(seed)) {
   seed = as.numeric(format(Sys.time(), "%OS6"))*1000000 #choose milliseconds of current time as seed
  }
  set.seed(seed)
  write(seed, file = file.path(output_directory, "seed.csv"))

  
  #Write input parameters to output_directory (this includes the seed used)
  write(toJSON(params, pretty=TRUE), file=file.path(output_directory, "params_used.json"))
  
  #Run model
  output = do.call(run_ABM, params)
  
  #Write model output
  write.csv(output, file=file.path(output_directory, "output.csv"), row.names=FALSE)
  
  #For convenience, also return output here
  return(output)
}




### Function to systematically run and save multiple runs of the model with the same parameter values.
# User designates the root output directory, parameter values, and the number of runs (numreps).
# Each run will be saved in its own named folder, which will contain the files created by run_model_single() described above
run_model_reps = function(params, root_output_directory, numreps=10) {
  for (rep in 1:numreps) {
    output_directory = file.path(root_output_directory, paste0("rep=", rep))
    run_model_single(params, output_directory)
  }
}




### Function to perform a sweep over specified values of a single parameter, holding all other values constant.
# This function wraps around the previous two functions. It produces a folder for each unique set of parameter values, 
# named for the parameter being swept, and its value in this set of runs. Inside the folder is a folder for each run (rep), containing the value of the random seed, the .json file of parameter values, and the output of the model run. 

#targetParam: the name of the parameter you want to sweep over
#targetParamValues: the VECTOR of values you want to sweep over 

# SzymonNowakowski's comment: 
# I have seen it executed only with a vector targetParamValues, not a list 
# and if you really want the code to support lists of values in targetParamValues
# change the below code according to a NOTE

run_model_sweep = function(base_params, root_output_directory, target_param, target_param_values, numreps=10) {
  for (iVal in 1:length(target_param_values)) {
    # for each unique value of the target parameter, name the folder to hold all runs of the model that uses this parameter value. 
    param_set_output_directory = file.path(root_output_directory, paste0(target_param, "=", target_param_values[iVal]))
    params = copy(base_params)
    # overwrite the default parameter value with the current value of the target parameter
    params[[target_param]] <- target_param_values[iVal]   #NOTE! IF YOU REALLY WANT IT TO WORK FOR LISTS, IT SHOULD READ SOMETHING LIKE <- unlist(target_param_values[iVal])
    
    run_model_reps(params, param_set_output_directory, numreps=numreps)
  }
  
  sweep_data = list()
  sweep_data["target_param"] = target_param
  sweep_data[["target_param_values"]] = target_param_values
  write(toJSON(sweep_data, pretty=TRUE), file=file.path(root_output_directory, "sweep_data.json"))
}




### Function to read in the data generated from a parameter sweep
read_model_sweep = function(root_output_directory, target_param = "prop_of_intra_household_interactions", target_param_values) {
  sweep_results = list()
  
  # for each value in the parameter being swept
  for (param_value in target_param_values) {
    param_dir = file.path(root_output_directory, paste0(target_param,"=", param_value)) # identify the directory where the output for that scenario is stored
    rep_dirs = list.dirs(param_dir, recursive = FALSE, full.names = TRUE) # identify the file paths for all the iterations/runs of that scenario
    
    # extract the output .csv file from each run
    rep_outputs = lapply(rep_dirs, function(rep_dir) {
      output_file = file.path(rep_dir, "output.csv")
      if (file.exists(output_file)) {
        return(read_csv(output_file))
      } else {
        print("file does not exist")
        return(NULL)
      }
    })
    
    # and save it as an entry in the sweep_results list, named with the target parameter value for this set of runs. 
    sweep_results[[paste0(target_param,"=",param_value)]] = rep_outputs
  }
  
  # return a list of lists: one for each value of the target parameter, containing a list of model output data frames from the output.csv files
  return(sweep_results)
}



# Example: How to use all these functions 
# params = get_default_params()
# single_test = run_model_single(params, output_directory = "output_directory")
# run_model_reps(params, "model_output/test_run", numreps=2)
# run_model_sweep(base_params = params, root_output_directory = "./Model 5.0/model_output/test_sweep", target_param = "prop_of_intra_household_interactions",
#                 target_param_values = c(0.25, 0.5, 0.75), numreps = 2)

